core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/',views.remove_single_item_from_cart , name= 'remove-single-item-from-cart'),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name='payment'),
    path('add-coupon/', views.add_coupon, name='add-coupon'),
]

ecommerce_website2/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

core/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('S','Shirt'),
    ('SW','Sport wear'),
    ('OW','Outwear')
)

LABLE_CHOICES = (
    ('P','primary'),
    ('S','secondary'),
    ('D','danger')
)

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABLE_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(blank=True, null=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug' : self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug' : self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug' : self.slug
        })

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey('Item', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    order_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link href="{% static "core/css/bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "core/css/mdb.min.css" %}" rel="stylesheet">
  <link href="{% static "core/css/style.min.css" %}" rel="stylesheet">
</head>


<body>

    {% include "navbar.html" %}

      <div class="mt-5 pt-4">
      {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
      {% endif %}
      </div>
  {% block content  %}

  {% endblock content %}

  {% block extra_body %}


  {% endblock %}



  {% include "footer.html" %}
  {% include "scripts.html" %}


</body>
</html>

templates/home-page.html
{% extends "base.html" %}
{% load static %}



{% block content %}

  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Welcom to my website</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

          
        <div class="row wow fadeIn">

          {% for item in object_list %}

          <div class="col-lg-3 col-md-6 mb-4">


            <div class="card">

              <!--Card image-->
              <div class="view overlay">
{#                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"#}
{#                  alt="">#}
                  <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                    {% if item.discount_price %}
                    {{ item.discount_price }}
                    {% else %}
                        {{ item.price }}
                    {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>

          {% endfor %}

        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->
      {% endif %}

    </div>
  </main>

{% endblock %}

templates/item_list.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

templates/navbar.html
{% load static %}
{% load cart_template_tags %}

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url "core:home" %}" target="_self">
        <strong class="blue-text">DJe-commerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url "core:home" %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url "core:checkout" %}" target="_self">Checkout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="#"
              target="_self">Products</a>
          </li>
{#          <li class="nav-item">#}
{#            <a class="nav-link waves-effect" href="https://mdbootstrap.com/education/bootstrap/" target="_blank">Free#}
{#              tutorials</a>#}
{#          </li>#}
        </ul>

              <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url "core:order-summary" %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url "account_logout" %}" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              <i class="fas fa-sign-out-alt mr-2"></i>Logout
            </a>
          </li>
{#          <li class="nav-item">#}
{#            <a href="https://www.facebook.com/mdbootstrap" class="nav-link waves-effect" target="_blank">#}
{#              <i class="fab fa-facebook-f"></i>#}
{#            </a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#            <a href="https://twitter.com/MDBootstrap" class="nav-link waves-effect" target="_blank">#}
{#              <i class="fab fa-twitter"></i>#}
{#            </a>#}
{#          </li>#}
          {% else %}
          <li class="nav-item">
            <a href="{% url "account_login" %}" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              <i class="fas fa-sign-in-alt mr-2"></i>Login
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url "account_signup" %}" class="nav-link border border-light rounded waves-effect"
                target="_blank">
             <i class="fas fa-user mr-3"></i>SignUp
            </a>
          </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

templates/order_snippet.html
<!--Grid column-->
<div class="col-md-12 mb-4">
  <!-- Heading -->
  <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
  </h4>
  <!-- Cart -->
  <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title }}</h6>
        <small class="text-muted">{{ order_item.item.description }}</small>
      </div>
      <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    <li class="list-group-item d-flex justify-content-between bg-light">
      <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
      </div>
      <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    <li class="list-group-item d-flex justify-content-between">
      <span>Total (USD)</span>
      <strong>${{ order.get_total }}</strong>
    </li>
  </ul>
  <!-- Cart -->
    {% if DISPLAY_COUPON_FORM %}
    <!-- Promo code -->
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
    {% csrf_token %}
    <div class="input-group">
{#      <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">#}
        {{ couponform.code }}
        <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
        </div>
    </div>
    </form>
    <!-- Promo code -->
    {% endif %}

</div>
<!--Grid column-->

templates/order_summary.html
{% extends "base.html" %}
{% load static %}



{% block content %}

    <main>
        <div class="container">
        <div class="table-responsive text-nowrap">
            <h2>Order Summary</h2>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Item Title</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total Item Price</th>
                  </tr>
                </thead>
                <tbody>
                  {% for order_item in object.items.all %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order_item.item.title }}</td>
                    <td>{{ order_item.item.price }}</td>
                    <td>
                        <a href="{% url "core:remove-single-item-from-cart" order_item.item.slug%}"><i class="fas fa-minus mr-2"></i></a>
                        {{ order_item.quantity }}
                        <a href="{% url "core:add-to-cart" order_item.item.slug%}"><i class="fas fa-plus ml-2"></i></a>
                    </td>
                    <td>
                    {% if order_item.item.discount_price %}
                        ${{ order_item.get_total_discount_item_price }}
                        <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                    {% else %}
                        ${{ order_item.get_total_item_price }}
                    {% endif %}
                    <a style="color: red" href="{% url "core:remove-from-cart" order_item.item.slug%}">
                        <i class="fas fa-trash float-right"></i>
                    </a>
                    </td>
                  </tr>
                  {% empty %}
                  <tr>
                    <td colspan="5">Your cart is empty</td>
                  </tr>
                  <tr>
                    <td colspan="5">
                        <a class="btn btn-primary float-lg-right" href="/">Continue Shopping</a>
                      </td>
                  </tr>
                  {% endfor %}
                  {% if object.get_total %}
                  <tr>
                    <td colspan="4"><b>Order Total</b></td>
                    <td><b>{{ object.get_total }}</b></td>
                  </tr>
                  <tr>
                      <td colspan="5">
                        <a class="btn btn-warning float-lg-right ml-2" href="/checkout/">Proced to checkout</a>
                        <a class="btn btn-primary float-lg-right" href="/">Continue Shopping</a>
                      </td>
                  </tr>
                  {% endif %}
                </tbody>
            </table>
        </div>
        </div>
    </main>

{% endblock %}

templates/product-page.html
{% extends "base.html" %}
{% load static %}



{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-5 mb-4">

          <img src="{{ item.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-7 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
{#              <a href="">#}
{#                <span class="badge blue mr-1">New</span>#}
{#              </a>#}
{#              <a href="">#}
{#                <span class="badge red mr-1">Bestseller</span>#}
{#              </a>#}
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>{{ object.discount_price }}</span>
              {% else %}
              <span>{{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

{#            <form class="d-flex justify-content-left">#}
{#              <!-- Default input -->#}
{#              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">#}
{#              <button class="btn btn-primary btn-md my-0 p" type="submit">#}
{#                  Add to cart#}
{#                <i class="fas fa-shopping-cart ml-1"></i>#}
{#              </button>#}
{##}
{#            </form>#}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                Remove from cart
               <i class="fas fa-trash ml-1"></i>
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
{% endblock %}

templates/scripts.html
{% load static %}
  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static "core/js/jquery-3.4.1.min.js" %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static "core/js/popper.min.js" %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static "core/js/bootstrap.min.js" %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static "core/js/mdb.min.js" %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>